language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

install:
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH

stages:
  - name: test

jobs:
  include:
    - stage: test
      script:
        - docker-compose up -d
        - mvn clean contraect:generate-contraects generate-sources test