peers: []

http:
  external:
    port: 3013
  internal:
    debug_endpoints: true
    port: 3113
    listen_address: 0.0.0.0
  endpoints:
    dry-run: true

chain:
  persist: true
  hard_forks:
    "1": 0
    "5": 1

websocket:
  channel:
    listen_address: 0.0.0.0
    port: 3014

mining:
  autostart: true
  beneficiary: "ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo"
  expected_mine_rate: 250
  micro_block_cycle: 100
  cuckoo:
    miner:
      executable: mean15-generic
      extra_args: ""
      edge_bits: 15

fork_management:
  network_id: ae_devnet

logging:
  level: debug