name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install libsodium
        run: |
          ./.github/scripts/install-libsodium.sh
          export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
      - name: Set Environment Variables
        run: |
          echo "AETERNITY_BASE_URL=http://localhost" >> $GITHUB_ENV
          echo "COMPILER_BASE_URL=http://localhost:3080" >> $GITHUB_ENV
          echo "INDAEX_BASE_URL=http://localhost:4000" >> $GITHUB_ENV
      - name: Start services
        run: docker-compose up -d
      - name: Execute tests
        run: mvn clean contraect:generate-contraects generate-sources test